<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestSuite_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>395896f7-2c83-4dff-9227-b7dcc1df8f36</testSuiteGuid>
   <testCaseLink>
      <guid>555820b6-cce4-4c10-ac91-beb49fe80c6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Partner Portal/RegistrationLoginPage/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cae3fb4f-e9aa-424d-8bee-6f7a2082641e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Credentials/Credentials</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cae3fb4f-e9aa-424d-8bee-6f7a2082641e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>d09651a9-8166-4bba-ab02-ffd15b258228</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cae3fb4f-e9aa-424d-8bee-6f7a2082641e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>9b1b1a5f-e2b0-481b-a65d-a02e06bfe397</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
